ETL Name:	wf_ACTIVATE.xml


Session 1: 	s_m_ACTIVATE
Mapping 1: 	m_PARAMETER_GENERATE


Source1 Name : SQ_WI_PROCESS_CONTROL


Pre SQL : 



SQL Query : 
select distinct 'The '||process_type||' Session has just got updated.' 
from $$TESTDB.WI_TEST_PROCESS_CONTROL 
WHERE  active_flag='Y'


Post SQL : 
update $$TESTDB.WI_TEST_PROCESS_CONTROL set active_flag='N' where process_type='TEST';

update $$TESTDB.WI_TEST_PROCESS_CONTROL set active_flag='Y' where process_type='FTEST';


/* to update process date for FTEST if process_date <current_date*/

UPDATE TEST FROM $$TESTDB.WI_TEST_PROCESS_CONTROL  TEST,
 (SELECT  min(FISCAL_MONTH_START_DATE) FISCAL_MONTH_START_DATE FROM $$COMREFVWDB.R_FISCAL_MONTH_TO_YEAR WHERE FISCAL_QTR_AGE=-1)  FISCAL
SET PROCESS_DATE=FISCAL.FISCAL_MONTH_START_DATE
WHERE PROCESS_DATE <=CURRENT_DATE
AND PROCESS_TYPE='FTEST';

/* commented as part of US422519 release */

/*DELETE FROM  $$TDB.MT_SLS_ACNT_RSTD_MSR_FTEST_NG WHERE  EXISTS 
(SELECT PROCESS_DATE FROM
$$TESTDB.WI_TEST_PROCESS_CONTROL
WHERE  ACTIVE_FLAG='Y' AND 
PROCESS_TYPE='FTEST'  ) ; */

UPDATE $$TESTDB.WI_TEST_PROCESS_CONTROL
SET BKG_EXTRACT_DATE=case when  (select FISCAL_MONTH_NUMBER_INT from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR  where calendar_date =current_date) IN (1,2) then (select MIN(CALENDAR_DATE) from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR 
WHERE FISCAL_YEAR_AGE<=3) else  (select MIN(CALENDAR_DATE) from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR 
WHERE FISCAL_YEAR_AGE<=2)  end 
WHERE ACTIVE_FLAG='Y'AND
PROCESS_TYPE = 'FTEST';

UPDATE $$TESTDB.WI_TEST_PROCESS_CONTROL
SET NAMD_ACNT_EXTRACT_DATE=case when  (select FISCAL_MONTH_NUMBER_INT from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR  where calendar_date =current_date) IN (1,2) then (select MIN(CALENDAR_DATE) from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR 
WHERE FISCAL_YEAR_AGE<=3) else  (select MIN(CALENDAR_DATE) from $$COMREFVWDB.R_FISCAL_DAY_TO_YEAR 
WHERE FISCAL_YEAR_AGE<=2)  end 
WHERE ACTIVE_FLAG='Y'AND
PROCESS_TYPE = 'FTEST';

DELETE FROM  $$TDB.RSTD_MSR_FTEST_NG WHERE BOOKINGS_PROCESS_DT<(
select    BKG_EXTRACT_DATE from $$TESTDB.WI_TEST_PROCESS_CONTROL where 
ACTIVE_FLAG='Y'AND
PROCESS_TYPE = 'FTEST');


/* DQ workflows wil be made inactive during fTEST refresh as part of July 5th rel*/
UPDATE $$TESTDB.DW_JOB_STREAMS SET ACTIVE_IND='N'
WHERE  job_stream_id in ('wf_WI_N_ADJSTMT_DQ','wf_W_SLS_ADJUSTMENT',
'wf_N_DYN_ADJSTMT') and exists (select 1 from $$TESTDB.WI_TEST_PROCESS_CONTROL WHERE ACTIVE_FLAG='Y'AND PROCESS_TYPE = 'FTEST');


Target1 Name : PROCESS_CONTROL_PARAMETER


Pre SQL : 



Post SQL : 
